
// This file has been generated by the GUI designer. Do not modify.
namespace QS.ChangePassword.Views
{
	public partial class ChangePasswordView
	{
		private global::Gamma.GtkWidgets.yVBox yvbox1;

		private global::Gamma.GtkWidgets.yTable ytable1;

		private global::Gamma.GtkWidgets.yEntry entryConfirmNewPassword;

		private global::Gamma.GtkWidgets.yEntry entryCurrentPassword;

		private global::Gamma.GtkWidgets.yEntry entryNewPassword;

		private global::Gamma.GtkWidgets.yLabel lblConfirmNewPassword;

		private global::Gamma.GtkWidgets.yLabel lblCurrentPassword;

		private global::Gamma.GtkWidgets.yLabel lblNewPassword;

		private global::Gtk.VBox vboxValidationResult;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.GtkWidgets.yToggleButton ytoggleShowCurrentPassword;

		private global::Gamma.GtkWidgets.yToggleButton ytoggleShowPassword;

		private global::Gamma.GtkWidgets.yHBox hboxActionBtns;

		private global::Gamma.GtkWidgets.yButton btnCancel;

		private global::Gamma.GtkWidgets.yButton btnSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.ChangePassword.Views.ChangePasswordView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.ChangePassword.Views.ChangePasswordView";
			// Container child QS.ChangePassword.Views.ChangePasswordView.Gtk.Container+ContainerChild
			this.yvbox1 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox1.Name = "yvbox1";
			this.yvbox1.Spacing = 6;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.ytable1 = new global::Gamma.GtkWidgets.yTable();
			this.ytable1.Name = "ytable1";
			this.ytable1.NRows = ((uint)(5));
			this.ytable1.NColumns = ((uint)(3));
			this.ytable1.RowSpacing = ((uint)(6));
			this.ytable1.ColumnSpacing = ((uint)(6));
			// Container child ytable1.Gtk.Table+TableChild
			this.entryConfirmNewPassword = new global::Gamma.GtkWidgets.yEntry();
			this.entryConfirmNewPassword.CanFocus = true;
			this.entryConfirmNewPassword.Name = "entryConfirmNewPassword";
			this.entryConfirmNewPassword.IsEditable = true;
			this.entryConfirmNewPassword.Visibility = false;
			this.entryConfirmNewPassword.InvisibleChar = '●';
			this.ytable1.Add(this.entryConfirmNewPassword);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.ytable1[this.entryConfirmNewPassword]));
			w1.TopAttach = ((uint)(3));
			w1.BottomAttach = ((uint)(4));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.entryCurrentPassword = new global::Gamma.GtkWidgets.yEntry();
			this.entryCurrentPassword.CanFocus = true;
			this.entryCurrentPassword.Name = "entryCurrentPassword";
			this.entryCurrentPassword.IsEditable = true;
			this.entryCurrentPassword.Visibility = false;
			this.entryCurrentPassword.InvisibleChar = '●';
			this.ytable1.Add(this.entryCurrentPassword);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.ytable1[this.entryCurrentPassword]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.entryNewPassword = new global::Gamma.GtkWidgets.yEntry();
			this.entryNewPassword.CanFocus = true;
			this.entryNewPassword.Name = "entryNewPassword";
			this.entryNewPassword.IsEditable = true;
			this.entryNewPassword.Visibility = false;
			this.entryNewPassword.InvisibleChar = '●';
			this.ytable1.Add(this.entryNewPassword);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.ytable1[this.entryNewPassword]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.lblConfirmNewPassword = new global::Gamma.GtkWidgets.yLabel();
			this.lblConfirmNewPassword.Name = "lblConfirmNewPassword";
			this.lblConfirmNewPassword.Xalign = 1F;
			this.lblConfirmNewPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Ещё раз:");
			this.ytable1.Add(this.lblConfirmNewPassword);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.ytable1[this.lblConfirmNewPassword]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.lblCurrentPassword = new global::Gamma.GtkWidgets.yLabel();
			this.lblCurrentPassword.Name = "lblCurrentPassword";
			this.lblCurrentPassword.Xalign = 1F;
			this.lblCurrentPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Текущий пароль:");
			this.ytable1.Add(this.lblCurrentPassword);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.ytable1[this.lblCurrentPassword]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.lblNewPassword = new global::Gamma.GtkWidgets.yLabel();
			this.lblNewPassword.Name = "lblNewPassword";
			this.lblNewPassword.Xalign = 1F;
			this.lblNewPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Новый пароль:");
			this.ytable1.Add(this.lblNewPassword);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.ytable1[this.lblNewPassword]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.vboxValidationResult = new global::Gtk.VBox();
			this.vboxValidationResult.Name = "vboxValidationResult";
			this.ytable1.Add(this.vboxValidationResult);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.ytable1[this.vboxValidationResult]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.RightAttach = ((uint)(3));
			// Container child ytable1.Gtk.Table+TableChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Пароль не должен содержать русских букв");
			this.ytable1.Add(this.ylabel1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ylabel1]));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ytable1.Gtk.Table+TableChild
			this.ytoggleShowCurrentPassword = new global::Gamma.GtkWidgets.yToggleButton();
			this.ytoggleShowCurrentPassword.CanFocus = true;
			this.ytoggleShowCurrentPassword.Name = "ytoggleShowCurrentPassword";
			this.ytoggleShowCurrentPassword.UseUnderline = true;
			global::Gtk.Image w9 = new global::Gtk.Image();
			w9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("QS.Icons.Eye.png");
			this.ytoggleShowCurrentPassword.Image = w9;
			this.ytable1.Add(this.ytoggleShowCurrentPassword);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ytoggleShowCurrentPassword]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(0));
			w10.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child ytable1.Gtk.Table+TableChild
			this.ytoggleShowPassword = new global::Gamma.GtkWidgets.yToggleButton();
			this.ytoggleShowPassword.CanFocus = true;
			this.ytoggleShowPassword.Name = "ytoggleShowPassword";
			this.ytoggleShowPassword.UseUnderline = true;
			global::Gtk.Image w11 = new global::Gtk.Image();
			w11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("QS.Icons.Eye.png");
			this.ytoggleShowPassword.Image = w11;
			this.ytable1.Add(this.ytoggleShowPassword);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.ytable1[this.ytoggleShowPassword]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(0));
			w12.YOptions = ((global::Gtk.AttachOptions)(0));
			this.yvbox1.Add(this.ytable1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.ytable1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.hboxActionBtns = new global::Gamma.GtkWidgets.yHBox();
			this.hboxActionBtns.Name = "hboxActionBtns";
			this.hboxActionBtns.Spacing = 6;
			// Container child hboxActionBtns.Gtk.Box+BoxChild
			this.btnCancel = new global::Gamma.GtkWidgets.yButton();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString("Отмена");
			this.hboxActionBtns.Add(this.btnCancel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxActionBtns[this.btnCancel]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hboxActionBtns.Gtk.Box+BoxChild
			this.btnSave = new global::Gamma.GtkWidgets.yButton();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			this.hboxActionBtns.Add(this.btnSave);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxActionBtns[this.btnSave]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.yvbox1.Add(this.hboxActionBtns);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.hboxActionBtns]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.yvbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
