
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Dialog.Views
{
	public partial class ProgressWindowView
	{
		private global::Gamma.GtkWidgets.yVBox yvbox1;

		private global::QS.Widgets.ProgressWidget progresswidget1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Dialog.Views.ProgressWindowView
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 500;
			this.Name = "QS.Dialog.Views.ProgressWindowView";
			// Container child QS.Dialog.Views.ProgressWindowView.Gtk.Container+ContainerChild
			this.yvbox1 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox1.Name = "yvbox1";
			this.yvbox1.Spacing = 6;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.progresswidget1 = new global::QS.Widgets.ProgressWidget();
			this.progresswidget1.Name = "progresswidget1";
			this.yvbox1.Add(this.progresswidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.progresswidget1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add(this.yvbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
