
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Navigation.GtkUI
{
	public partial class TabPageTitleView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Navigation.GtkUI.TabPageTitleView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Navigation.GtkUI.TabPageTitleView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
