
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Navigation.GtkUI
{
	public partial class TabNavigatorView
	{
		private global::Gtk.HBox hboxContent;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Navigation.GtkUI.TabNavigatorView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Navigation.GtkUI.TabNavigatorView";
			// Container child QS.Navigation.GtkUI.TabNavigatorView.Gtk.Container+ContainerChild
			this.hboxContent = new global::Gtk.HBox();
			this.hboxContent.Name = "hboxContent";
			this.hboxContent.Spacing = 6;
			this.Add(this.hboxContent);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
