
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Project.Versioning.Views
{
	public partial class ChangeLogView
	{
		private global::Gamma.GtkWidgets.yVBox yvbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTextView ytextviewLog;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Project.Versioning.Views.ChangeLogView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Project.Versioning.Views.ChangeLogView";
			// Container child QS.Project.Versioning.Views.ChangeLogView.Gtk.Container+ContainerChild
			this.yvbox1 = new global::Gamma.GtkWidgets.yVBox();
			this.yvbox1.Name = "yvbox1";
			this.yvbox1.Spacing = 6;
			// Container child yvbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytextviewLog = new global::Gamma.GtkWidgets.yTextView();
			this.ytextviewLog.CanFocus = true;
			this.ytextviewLog.Name = "ytextviewLog";
			this.ytextviewLog.Editable = false;
			this.GtkScrolledWindow.Add(this.ytextviewLog);
			this.yvbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.yvbox1[this.GtkScrolledWindow]));
			w2.Position = 1;
			this.Add(this.yvbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
