
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Project.Dialogs.GtkUI
{
	public partial class RepresentationJournalDialog
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hboxButtons;

		private global::Gtk.HBox hboxSelect;

		private global::Gtk.Button buttonSelect;

		private global::Gtk.VSeparator vseparatorSelect;

		private global::Gtk.CheckButton checkShowFilter;

		private global::Gtk.Button buttonRefresh;

		private global::Gtk.HBox hboxFilter;

		private global::Gtk.HBox hboxSearch;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entrySearch;

		private global::Gamma.GtkWidgets.yLabel ylabelSearchAnd;

		private global::Gtk.Entry entrySearch2;

		private global::Gamma.GtkWidgets.yLabel ylabelSearchAnd2;

		private global::Gtk.Entry entrySearch3;

		private global::Gamma.GtkWidgets.yLabel ylabelSearchAnd3;

		private global::Gtk.Entry entrySearch4;

		private global::Gtk.Button buttonAddAnd;

		private global::Gtk.Button buttonSearchClear;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::QS.Widgets.GtkUI.RepresentationTreeView tableview;

		private global::Gtk.Label labelSum;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Project.Dialogs.GtkUI.RepresentationJournalDialog
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Project.Dialogs.GtkUI.RepresentationJournalDialog";
			// Container child QS.Project.Dialogs.GtkUI.RepresentationJournalDialog.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.hboxSelect = new global::Gtk.HBox();
			this.hboxSelect.Name = "hboxSelect";
			this.hboxSelect.Spacing = 6;
			// Container child hboxSelect.Gtk.Box+BoxChild
			this.buttonSelect = new global::Gtk.Button();
			this.buttonSelect.Sensitive = false;
			this.buttonSelect.CanFocus = true;
			this.buttonSelect.Name = "buttonSelect";
			this.buttonSelect.UseUnderline = true;
			this.buttonSelect.Label = global::Mono.Unix.Catalog.GetString("Выбрать");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-index", global::Gtk.IconSize.Menu);
			this.buttonSelect.Image = w1;
			this.hboxSelect.Add(this.buttonSelect);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxSelect[this.buttonSelect]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxSelect.Gtk.Box+BoxChild
			this.vseparatorSelect = new global::Gtk.VSeparator();
			this.vseparatorSelect.Name = "vseparatorSelect";
			this.hboxSelect.Add(this.vseparatorSelect);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxSelect[this.vseparatorSelect]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hboxButtons.Add(this.hboxSelect);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.hboxSelect]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.checkShowFilter = new global::Gtk.CheckButton();
			this.checkShowFilter.CanFocus = true;
			this.checkShowFilter.Name = "checkShowFilter";
			this.checkShowFilter.Label = global::Mono.Unix.Catalog.GetString("Фильтр");
			this.checkShowFilter.DrawIndicator = false;
			this.checkShowFilter.UseUnderline = true;
			this.hboxButtons.Add(this.checkShowFilter);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.checkShowFilter]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.buttonRefresh = new global::Gtk.Button();
			this.buttonRefresh.CanFocus = true;
			this.buttonRefresh.Name = "buttonRefresh";
			this.buttonRefresh.UseUnderline = true;
			this.buttonRefresh.Label = global::Mono.Unix.Catalog.GetString("Обновить");
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.buttonRefresh.Image = w6;
			this.hboxButtons.Add(this.buttonRefresh);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.buttonRefresh]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add(this.hboxButtons);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxButtons]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxFilter = new global::Gtk.HBox();
			this.hboxFilter.Name = "hboxFilter";
			this.hboxFilter.Spacing = 6;
			this.vbox1.Add(this.hboxFilter);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxFilter]));
			w9.Position = 1;
			w9.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxSearch = new global::Gtk.HBox();
			this.hboxSearch.Name = "hboxSearch";
			this.hboxSearch.Spacing = 6;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Поиск:");
			this.hboxSearch.Add(this.label1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.label1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch = new global::Gtk.Entry();
			this.entrySearch.WidthRequest = 50;
			this.entrySearch.CanFocus = true;
			this.entrySearch.Name = "entrySearch";
			this.entrySearch.IsEditable = true;
			this.entrySearch.InvisibleChar = '●';
			this.hboxSearch.Add(this.entrySearch);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.entrySearch]));
			w11.Position = 1;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.ylabelSearchAnd = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelSearchAnd.Name = "ylabelSearchAnd";
			this.ylabelSearchAnd.LabelProp = global::Mono.Unix.Catalog.GetString("и");
			this.hboxSearch.Add(this.ylabelSearchAnd);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.ylabelSearchAnd]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch2 = new global::Gtk.Entry();
			this.entrySearch2.WidthRequest = 50;
			this.entrySearch2.CanFocus = true;
			this.entrySearch2.Name = "entrySearch2";
			this.entrySearch2.IsEditable = true;
			this.entrySearch2.InvisibleChar = '●';
			this.hboxSearch.Add(this.entrySearch2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.entrySearch2]));
			w13.Position = 3;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.ylabelSearchAnd2 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelSearchAnd2.Name = "ylabelSearchAnd2";
			this.ylabelSearchAnd2.LabelProp = global::Mono.Unix.Catalog.GetString("и");
			this.hboxSearch.Add(this.ylabelSearchAnd2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.ylabelSearchAnd2]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch3 = new global::Gtk.Entry();
			this.entrySearch3.WidthRequest = 50;
			this.entrySearch3.CanFocus = true;
			this.entrySearch3.Name = "entrySearch3";
			this.entrySearch3.IsEditable = true;
			this.entrySearch3.InvisibleChar = '●';
			this.hboxSearch.Add(this.entrySearch3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.entrySearch3]));
			w15.Position = 5;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.ylabelSearchAnd3 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelSearchAnd3.Name = "ylabelSearchAnd3";
			this.ylabelSearchAnd3.LabelProp = global::Mono.Unix.Catalog.GetString("и");
			this.hboxSearch.Add(this.ylabelSearchAnd3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.ylabelSearchAnd3]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch4 = new global::Gtk.Entry();
			this.entrySearch4.WidthRequest = 50;
			this.entrySearch4.CanFocus = true;
			this.entrySearch4.Name = "entrySearch4";
			this.entrySearch4.IsEditable = true;
			this.entrySearch4.InvisibleChar = '●';
			this.hboxSearch.Add(this.entrySearch4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.entrySearch4]));
			w17.Position = 7;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.buttonAddAnd = new global::Gtk.Button();
			this.buttonAddAnd.CanFocus = true;
			this.buttonAddAnd.Name = "buttonAddAnd";
			this.buttonAddAnd.UseUnderline = true;
			this.buttonAddAnd.Label = global::Mono.Unix.Catalog.GetString("И");
			global::Gtk.Image w18 = new global::Gtk.Image();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddAnd.Image = w18;
			this.hboxSearch.Add(this.buttonAddAnd);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.buttonAddAnd]));
			w19.Position = 8;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.buttonSearchClear = new global::Gtk.Button();
			this.buttonSearchClear.TooltipMarkup = "Очистить";
			this.buttonSearchClear.CanFocus = true;
			this.buttonSearchClear.Name = "buttonSearchClear";
			this.buttonSearchClear.UseUnderline = true;
			global::Gtk.Image w20 = new global::Gtk.Image();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.buttonSearchClear.Image = w20;
			this.hboxSearch.Add(this.buttonSearchClear);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hboxSearch[this.buttonSearchClear]));
			w21.Position = 9;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add(this.hboxSearch);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxSearch]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tableview = new global::QS.Widgets.GtkUI.RepresentationTreeView();
			this.tableview.CanFocus = true;
			this.tableview.Name = "tableview";
			this.GtkScrolledWindow.Add(this.tableview);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w24.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelSum = new global::Gtk.Label();
			this.labelSum.Name = "labelSum";
			this.labelSum.Xpad = 6;
			this.labelSum.Xalign = 1F;
			this.labelSum.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.labelSum.SingleLineMode = true;
			this.vbox1.Add(this.labelSum);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelSum]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.checkShowFilter.Hide();
			this.hboxFilter.Hide();
			this.ylabelSearchAnd.Hide();
			this.entrySearch2.Hide();
			this.ylabelSearchAnd2.Hide();
			this.entrySearch3.Hide();
			this.ylabelSearchAnd3.Hide();
			this.entrySearch4.Hide();
			this.Hide();
			this.buttonSelect.Clicked += new global::System.EventHandler(this.OnButtonSelectClicked);
			this.buttonRefresh.Clicked += new global::System.EventHandler(this.OnButtonRefreshClicked);
			this.checkShowFilter.Toggled += new global::System.EventHandler(this.OnCheckShowFilterToggled);
			this.entrySearch.Changed += new global::System.EventHandler(this.OnEntrySearchChanged);
			this.entrySearch2.Changed += new global::System.EventHandler(this.OnEntrySearchChanged);
			this.entrySearch3.Changed += new global::System.EventHandler(this.OnEntrySearchChanged);
			this.entrySearch4.Changed += new global::System.EventHandler(this.OnEntrySearchChanged);
			this.buttonAddAnd.Clicked += new global::System.EventHandler(this.OnButtonAddAndClicked);
			this.buttonSearchClear.Clicked += new global::System.EventHandler(this.OnButtonSearchClearClicked);
			this.tableview.RowActivated += new global::Gtk.RowActivatedHandler(this.OnOrmtableviewRowActivated);
		}
	}
}
