
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Views.Control
{
	public partial class EntitySearch
	{
		private global::Gtk.HBox hbox2;

		private global::Gamma.GtkWidgets.yEntry tbTextForSearch;

		private global::Gtk.Button btnClear;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Views.Control.EntitySearch
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Views.Control.EntitySearch";
			// Container child QS.Views.Control.EntitySearch.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.tbTextForSearch = new global::Gamma.GtkWidgets.yEntry();
			this.tbTextForSearch.CanFocus = true;
			this.tbTextForSearch.Name = "tbTextForSearch";
			this.tbTextForSearch.IsEditable = true;
			this.tbTextForSearch.InvisibleChar = '●';
			this.hbox2.Add(this.tbTextForSearch);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.tbTextForSearch]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnClear = new global::Gtk.Button();
			this.btnClear.TooltipMarkup = "Удаление";
			this.btnClear.Sensitive = false;
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.btnClear.Image = w2;
			this.hbox2.Add(this.btnClear);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnClear]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.tbTextForSearch.WidgetEvent += new global::Gtk.WidgetEventHandler(this.OnEntryObjectWidgetEvent);
			this.tbTextForSearch.Changed += new global::System.EventHandler(this.OnEntryObjectChanged);
			this.btnClear.Clicked += new global::System.EventHandler(this.OnButtonClearClicked);
		}
	}
}
