
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Widgets.GtkUI
{
	public partial class DateRangePicker
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry entryDate;

		private global::Gtk.Button buttonClearDate;

		private global::Gtk.Button buttonPickDatePeriod;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Widgets.GtkUI.DateRangePicker
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Widgets.GtkUI.DateRangePicker";
			// Container child QS.Widgets.GtkUI.DateRangePicker.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryDate = new global::Gtk.Entry();
			this.entryDate.CanFocus = true;
			this.entryDate.Name = "entryDate";
			this.entryDate.IsEditable = true;
			this.entryDate.MaxLength = 23;
			this.entryDate.InvisibleChar = '●';
			this.hbox1.Add(this.entryDate);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryDate]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClearDate = new global::Gtk.Button();
			this.buttonClearDate.CanFocus = true;
			this.buttonClearDate.Name = "buttonClearDate";
			this.buttonClearDate.UseUnderline = true;
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.buttonClearDate.Image = w2;
			this.hbox1.Add(this.buttonClearDate);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonClearDate]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonPickDatePeriod = new global::Gtk.Button();
			this.buttonPickDatePeriod.CanFocus = true;
			this.buttonPickDatePeriod.Name = "buttonPickDatePeriod";
			this.buttonPickDatePeriod.UseUnderline = true;
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("QS.Icons.DateRange.png");
			this.buttonPickDatePeriod.Image = w4;
			this.hbox1.Add(this.buttonPickDatePeriod);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonPickDatePeriod]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.entryDate.FocusOutEvent += new global::Gtk.FocusOutEventHandler(this.OnEntryDateFocusOutEvent);
			this.entryDate.Changed += new global::System.EventHandler(this.OnEntryDateChanged);
			this.buttonClearDate.Clicked += new global::System.EventHandler(this.OnButtonClearDateClicked);
			this.buttonPickDatePeriod.Clicked += new global::System.EventHandler(this.OnButtonPickDatePeriodClicked);
		}
	}
}
