
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Widgets.Gtk
{
	public partial class UserPermissionWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Notebook notebook1;

		private global::QS.Widgets.Gtk.UserEntityPermissionWidget userEntityPermissionsView;

		private global::Gtk.Label label1;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Widgets.Gtk.UserPermissionWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Widgets.Gtk.UserPermissionWidget";
			// Container child QS.Widgets.Gtk.UserPermissionWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.userEntityPermissionsView = new global::QS.Widgets.Gtk.UserEntityPermissionWidget();
			this.userEntityPermissionsView.Events = ((global::Gdk.EventMask)(256));
			this.userEntityPermissionsView.Name = "userEntityPermissionsView";
			this.notebook1.Add(this.userEntityPermissionsView);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Для документов");
			this.notebook1.SetTabLabel(this.userEntityPermissionsView, this.label1);
			this.label1.ShowAll();
			// Notebook tab
			global::Gtk.Label w2 = new global::Gtk.Label();
			w2.Visible = true;
			this.notebook1.Add(w2);
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Прочие");
			this.notebook1.SetTabLabel(w2, this.label3);
			this.label3.ShowAll();
			this.vbox1.Add(this.notebook1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
			w3.Position = 0;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
