
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Widgets.GtkUI
{
	public partial class UserEntityPermissionWidget
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewEntitiesList;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Button buttonAdd;

		private global::QS.Project.Dialogs.PermissionListView permissionlistview;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entrySearchText;

		private global::Gtk.Button buttonClear;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Widgets.GtkUI.UserEntityPermissionWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Widgets.GtkUI.UserEntityPermissionWidget";
			// Container child QS.Widgets.GtkUI.UserEntityPermissionWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ytreeviewEntitiesList = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewEntitiesList.CanFocus = true;
			this.ytreeviewEntitiesList.Name = "ytreeviewEntitiesList";
			this.GtkScrolledWindow1.Add(this.ytreeviewEntitiesList);
			this.hbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonAdd = new global::Gtk.Button();
			this.buttonAdd.CanFocus = true;
			this.buttonAdd.Name = "buttonAdd";
			this.buttonAdd.UseUnderline = true;
			this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString(">");
			this.vbox1.Add(this.buttonAdd);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonAdd]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox2.Add(this.vbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.permissionlistview = new global::QS.Project.Dialogs.PermissionListView();
			this.permissionlistview.Events = ((global::Gdk.EventMask)(256));
			this.permissionlistview.Name = "permissionlistview";
			this.hbox2.Add(this.permissionlistview);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.permissionlistview]));
			w5.Position = 2;
			w5.Expand = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w6.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Поиск:");
			this.hbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entrySearchText = new global::Gtk.Entry();
			this.entrySearchText.TooltipMarkup = "Введите фразу для поиска";
			this.entrySearchText.CanFocus = true;
			this.entrySearchText.Name = "entrySearchText";
			this.entrySearchText.IsEditable = true;
			this.entrySearchText.InvisibleChar = '●';
			this.hbox3.Add(this.entrySearchText);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entrySearchText]));
			w8.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button();
			this.buttonClear.TooltipMarkup = "Очистить поисковую фразу";
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			global::Gtk.Image w9 = new global::Gtk.Image();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.buttonClear.Image = w9;
			this.hbox3.Add(this.buttonClear);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonClear]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.ytreeviewEntitiesList.RowActivated += new global::Gtk.RowActivatedHandler(this.OnYtreeviewEntitiesListRowActivated);
			this.buttonAdd.Clicked += new global::System.EventHandler(this.OnButtonAddClicked);
			this.entrySearchText.Changed += new global::System.EventHandler(this.SearchDocumentsOnTextChanged);
			this.buttonClear.Clicked += new global::System.EventHandler(this.OnButtonClearClicked);
		}
	}
}
