
// This file has been generated by the GUI designer. Do not modify.
namespace QSPhones
{
	public partial class PhonesView
	{
		private global::Gtk.DataBindings.DataTable datatable1;
		
		private global::Gtk.DataBindings.DataComboBox comboType;
		
		private global::Gtk.DataBindings.DataEntry entryAdditional;
		
		private global::Gtk.DataBindings.DataEntry entryPhone;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QSPhones.PhonesView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "QSPhones.PhonesView";
			// Container child QSPhones.PhonesView.Gtk.Container+ContainerChild
			this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(1)), ((uint)(5)), false);
			this.datatable1.Name = "datatable1";
			this.datatable1.RowSpacing = ((uint)(6));
			this.datatable1.ColumnSpacing = ((uint)(6));
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			// Container child datatable1.Gtk.Table+TableChild
			this.comboType = new global::Gtk.DataBindings.DataComboBox ();
			this.comboType.WidthRequest = 100;
			this.comboType.Name = "comboType";
			this.comboType.InheritedDataSource = false;
			this.comboType.InheritedBoundaryDataSource = false;
			this.comboType.CursorPointsEveryType = false;
			this.comboType.InheritedDataSource = false;
			this.comboType.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.comboType);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.comboType]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.entryAdditional = new global::Gtk.DataBindings.DataEntry ();
			this.entryAdditional.WidthRequest = 50;
			this.entryAdditional.CanFocus = true;
			this.entryAdditional.Name = "entryAdditional";
			this.entryAdditional.IsEditable = true;
			this.entryAdditional.InvisibleChar = '●';
			this.entryAdditional.InheritedDataSource = false;
			this.entryAdditional.InheritedBoundaryDataSource = false;
			this.entryAdditional.InheritedDataSource = false;
			this.entryAdditional.InheritedBoundaryDataSource = false;
			this.entryAdditional.Editable = false;
			this.datatable1.Add (this.entryAdditional);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.entryAdditional]));
			w2.LeftAttach = ((uint)(4));
			w2.RightAttach = ((uint)(5));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.entryPhone = new global::Gtk.DataBindings.DataEntry ();
			this.entryPhone.CanFocus = true;
			this.entryPhone.Name = "entryPhone";
			this.entryPhone.IsEditable = true;
			this.entryPhone.WidthChars = 19;
			this.entryPhone.InvisibleChar = '●';
			this.entryPhone.InheritedDataSource = false;
			this.entryPhone.InheritedBoundaryDataSource = false;
			this.entryPhone.InheritedDataSource = false;
			this.entryPhone.InheritedBoundaryDataSource = false;
			this.entryPhone.Editable = false;
			this.datatable1.Add (this.entryPhone);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.entryPhone]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("+7");
			this.datatable1.Add (this.label1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label1]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("доб.");
			this.datatable1.Add (this.label2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label2]));
			w5.LeftAttach = ((uint)(3));
			w5.RightAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.datatable1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.entryPhone.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryPhoneTextInserted);
			this.entryPhone.TextDeleted += new global::Gtk.TextDeletedHandler (this.OnEntryPhoneTextDeleted);
		}
	}
}
