
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Launcher.Views
{
	public partial class MainWindow
	{
		private global::Gamma.GtkWidgets.yNotebook notebookMain;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Launcher.Views.MainWindow
			this.Name = "QS.Launcher.Views.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child QS.Launcher.Views.MainWindow.Gtk.Container+ContainerChild
			this.notebookMain = new global::Gamma.GtkWidgets.yNotebook();
			this.notebookMain.CanFocus = true;
			this.notebookMain.Name = "notebookMain";
			this.notebookMain.CurrentPage = -1;
			this.notebookMain.ShowBorder = false;
			this.Add(this.notebookMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
