
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Launcher.Views
{
	public partial class LoginView
	{
		private global::Gamma.GtkWidgets.yVBox vbox2;

		private global::Gamma.GtkWidgets.yImage imageLogo;

		private global::Gamma.GtkWidgets.yLabel labelAppName;

		private global::Gtk.Table table1;

		private global::Gamma.GtkWidgets.yButton buttonEditConnection;

		private global::Gamma.Widgets.yListComboBox comboboxConnections;

		private global::Gamma.GtkWidgets.yEntry entryPassword;

		private global::Gamma.GtkWidgets.yEntry entryUser;

		private global::Gamma.GtkWidgets.yLabel label1;

		private global::Gamma.GtkWidgets.yLabel label2;

		private global::Gamma.GtkWidgets.yLabel label3;

		private global::Gamma.GtkWidgets.yLabel label4;

		private global::Gamma.GtkWidgets.yLabel label5;

		private global::Gamma.GtkWidgets.yLabel labelKeyboardLayoutInfo;

		private global::Gamma.GtkWidgets.yLabel labelCapslockInfo;

		private global::Gamma.GtkWidgets.yButton buttonLogin;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Launcher.Views.LoginView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Launcher.Views.LoginView";
			// Container child QS.Launcher.Views.LoginView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gamma.GtkWidgets.yVBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.imageLogo = new global::Gamma.GtkWidgets.yImage();
			this.imageLogo.WidthRequest = 0;
			this.imageLogo.HeightRequest = 0;
			this.imageLogo.Name = "imageLogo";
			this.vbox2.Add(this.imageLogo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.imageLogo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelAppName = new global::Gamma.GtkWidgets.yLabel();
			this.labelAppName.Name = "labelAppName";
			this.labelAppName.Xpad = 25;
			this.labelAppName.Xalign = 1F;
			this.labelAppName.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"gray\" size=\"large\" font_family=\"Philosopher\"><b>QS: Платформа v" +
					".1.0</b></span>");
			this.labelAppName.UseMarkup = true;
			this.labelAppName.Justify = ((global::Gtk.Justification)(1));
			this.vbox2.Add(this.labelAppName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelAppName]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(18));
			// Container child table1.Gtk.Table+TableChild
			this.buttonEditConnection = new global::Gamma.GtkWidgets.yButton();
			this.buttonEditConnection.TooltipMarkup = "Редактор подключений";
			this.buttonEditConnection.CanFocus = true;
			this.buttonEditConnection.Name = "buttonEditConnection";
			this.buttonEditConnection.UseUnderline = true;
			this.buttonEditConnection.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonEditConnection.Image = w3;
			this.table1.Add(this.buttonEditConnection);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.buttonEditConnection]));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxConnections = new global::Gamma.Widgets.yListComboBox();
			this.comboboxConnections.Name = "comboboxConnections";
			this.comboboxConnections.AddIfNotExist = false;
			this.comboboxConnections.DefaultFirst = false;
			this.table1.Add(this.comboboxConnections);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.comboboxConnections]));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryPassword = new global::Gamma.GtkWidgets.yEntry();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.Visibility = false;
			this.entryPassword.InvisibleChar = '●';
			this.table1.Add(this.entryPassword);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.entryPassword]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryUser = new global::Gamma.GtkWidgets.yEntry();
			this.entryUser.CanFocus = true;
			this.entryUser.Name = "entryUser";
			this.entryUser.IsEditable = true;
			this.entryUser.InvisibleChar = '●';
			this.table1.Add(this.entryUser);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.entryUser]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gamma.GtkWidgets.yLabel();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Пользователь:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gamma.GtkWidgets.yLabel();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Пароль:");
			this.label2.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gamma.GtkWidgets.yLabel();
			this.label3.Name = "label3";
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gamma.GtkWidgets.yLabel();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Подключение:");
			this.label4.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gamma.GtkWidgets.yLabel();
			this.label5.Name = "label5";
			this.table1.Add(this.label5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w12.LeftAttach = ((uint)(4));
			w12.RightAttach = ((uint)(5));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add(this.table1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelKeyboardLayoutInfo = new global::Gamma.GtkWidgets.yLabel();
			this.labelKeyboardLayoutInfo.Name = "labelKeyboardLayoutInfo";
			this.labelKeyboardLayoutInfo.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"red\"><b>Внимание: включен русский язык</b></span>");
			this.labelKeyboardLayoutInfo.UseMarkup = true;
			this.vbox2.Add(this.labelKeyboardLayoutInfo);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelKeyboardLayoutInfo]));
			w14.Position = 3;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelCapslockInfo = new global::Gamma.GtkWidgets.yLabel();
			this.labelCapslockInfo.Name = "labelCapslockInfo";
			this.labelCapslockInfo.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"red\"><b>Внимание: включен Caps Lock</b></span>");
			this.labelCapslockInfo.UseMarkup = true;
			this.vbox2.Add(this.labelCapslockInfo);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelCapslockInfo]));
			w15.Position = 4;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonLogin = new global::Gamma.GtkWidgets.yButton();
			this.buttonLogin.CanFocus = true;
			this.buttonLogin.Name = "buttonLogin";
			this.buttonLogin.UseUnderline = true;
			this.buttonLogin.Label = global::Mono.Unix.Catalog.GetString("Войти");
			this.vbox2.Add(this.buttonLogin);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonLogin]));
			w16.Position = 5;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.entryUser.Hide();
			this.label1.Hide();
			this.labelKeyboardLayoutInfo.Hide();
			this.labelCapslockInfo.Hide();
			this.Hide();
			this.entryPassword.Activated += new global::System.EventHandler(this.OnEntryPasswordActivated);
			this.buttonLogin.Clicked += new global::System.EventHandler(this.OnButtonLoginClicked);
		}
	}
}
