
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Report.Views
{
	public partial class SelectablePrintersView
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label labelPrinters;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewPrinters;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Table table1;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Label labelGeneralSettings;

		private global::Gtk.Label labelNumberOfCopies;

		private global::Gtk.Label labelPageOrientation;

		private global::Gamma.Widgets.yEnumComboBox yenumcomboboxPageOrientation;

		private global::Gamma.GtkWidgets.ySpinButton yspinbuttonNumberOfCopies;

		private global::Gtk.HSeparator hseparator4;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button buttonOpenSettings;

		private global::Gtk.Button buttonSaveSettings;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOK;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Report.Views.SelectablePrintersView
			this.Name = "QS.Report.Views.SelectablePrintersView";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child QS.Report.Views.SelectablePrintersView.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelPrinters = new global::Gtk.Label();
			this.labelPrinters.Name = "labelPrinters";
			this.labelPrinters.LabelProp = global::Mono.Unix.Catalog.GetString("Выбранные принтеры");
			this.vbox2.Add(this.labelPrinters);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelPrinters]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.ytreeviewPrinters = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewPrinters.CanFocus = true;
			this.ytreeviewPrinters.Name = "ytreeviewPrinters";
			this.scrolledwindow1.Add(this.ytreeviewPrinters);
			this.vbox2.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow1]));
			w5.Position = 2;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.table1.Add(this.hseparator3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator3]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelGeneralSettings = new global::Gtk.Label();
			this.labelGeneralSettings.Name = "labelGeneralSettings";
			this.labelGeneralSettings.LabelProp = global::Mono.Unix.Catalog.GetString("Общие настройки");
			this.table1.Add(this.labelGeneralSettings);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.labelGeneralSettings]));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNumberOfCopies = new global::Gtk.Label();
			this.labelNumberOfCopies.Name = "labelNumberOfCopies";
			this.labelNumberOfCopies.Xalign = 0F;
			this.labelNumberOfCopies.LabelProp = global::Mono.Unix.Catalog.GetString("Кол-во копий:");
			this.table1.Add(this.labelNumberOfCopies);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.labelNumberOfCopies]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelPageOrientation = new global::Gtk.Label();
			this.labelPageOrientation.Name = "labelPageOrientation";
			this.labelPageOrientation.Xalign = 0F;
			this.labelPageOrientation.LabelProp = global::Mono.Unix.Catalog.GetString("Ориентация:");
			this.table1.Add(this.labelPageOrientation);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.labelPageOrientation]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.yenumcomboboxPageOrientation = new global::Gamma.Widgets.yEnumComboBox();
            this.yenumcomboboxPageOrientation.Name = "yenumcomboboxPageOrientation";
			this.yenumcomboboxPageOrientation.ShowSpecialStateAll = false;
			this.yenumcomboboxPageOrientation.ShowSpecialStateNot = false;
			this.yenumcomboboxPageOrientation.UseShortTitle = false;
			this.yenumcomboboxPageOrientation.DefaultFirst = true;
			this.table1.Add(this.yenumcomboboxPageOrientation);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.yenumcomboboxPageOrientation]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.yspinbuttonNumberOfCopies = new global::Gamma.GtkWidgets.ySpinButton(0D, 255D, 1D);
			this.yspinbuttonNumberOfCopies.CanFocus = true;
			this.yspinbuttonNumberOfCopies.Name = "yspinbuttonNumberOfCopies";
			this.yspinbuttonNumberOfCopies.Adjustment.PageIncrement = 5D;
			this.yspinbuttonNumberOfCopies.ClimbRate = 1D;
			this.yspinbuttonNumberOfCopies.Numeric = true;
			this.yspinbuttonNumberOfCopies.ValueAsDecimal = 0m;
			this.yspinbuttonNumberOfCopies.ValueAsInt = 0;
			this.table1.Add(this.yspinbuttonNumberOfCopies);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.yspinbuttonNumberOfCopies]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table1]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			w1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(w1[this.hbox1]));
			w15.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator();
			this.hseparator4.Name = "hseparator4";
			w1.Add(this.hseparator4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(w1[this.hseparator4]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonOpenSettings = new global::Gtk.Button();
			this.buttonOpenSettings.CanFocus = true;
			this.buttonOpenSettings.Name = "buttonOpenSettings";
			this.buttonOpenSettings.UseUnderline = true;
			this.buttonOpenSettings.Label = global::Mono.Unix.Catalog.GetString("Настройки принтера");
			this.hbox2.Add(this.buttonOpenSettings);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonOpenSettings]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonSaveSettings = new global::Gtk.Button();
			this.buttonSaveSettings.CanDefault = true;
			this.buttonSaveSettings.CanFocus = true;
			this.buttonSaveSettings.Name = "buttonSaveSettings";
			this.buttonSaveSettings.UseUnderline = true;
			this.buttonSaveSettings.Label = global::Mono.Unix.Catalog.GetString("Сохранить настройки печати");
			this.hbox2.Add(this.buttonSaveSettings);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonSaveSettings]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(w1[this.hbox2]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Internal child QS.Report.Views.SelectablePrintersView.ActionArea
			global::Gtk.HButtonBox w20 = this.ActionArea;
			w20.Name = "dialog1_ActionArea";
			w20.Spacing = 10;
			w20.BorderWidth = ((uint)(5));
			w20.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w20[this.buttonCancel]));
			w21.Expand = false;
			w21.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOK = new global::Gtk.Button();
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseStock = true;
			this.buttonOK.UseUnderline = true;
			this.buttonOK.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOK, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w20[this.buttonOK]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 598;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
