
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Test.TestApp.Views
{
	public partial class DialogWithDocumentationView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Test.TestApp.Views.DialogWithDocumentationView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Test.TestApp.Views.DialogWithDocumentationView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
