//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace QS.Banks.Contracts {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cbr-ru:ed:v2.0", IsNullable=false)]
    public partial class ED807 : ESIDWithPartInfo {
        
        private BICDirectoryEntryType[] bICDirectoryEntryField;
        
        private ReasonCodeType creationReasonField;
        
        private System.DateTime creationDateTimeField;
        
        private RequestCodeType infoTypeCodeField;
        
        private System.DateTime businessDayField;
        
        private string directoryVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BICDirectoryEntry")]
        public BICDirectoryEntryType[] BICDirectoryEntry {
            get {
                return this.bICDirectoryEntryField;
            }
            set {
                this.bICDirectoryEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReasonCodeType CreationReason {
            get {
                return this.creationReasonField;
            }
            set {
                this.creationReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequestCodeType InfoTypeCode {
            get {
                return this.infoTypeCodeField;
            }
            set {
                this.infoTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime BusinessDay {
            get {
                return this.businessDayField;
            }
            set {
                this.businessDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string DirectoryVersion {
            get {
                return this.directoryVersionField;
            }
            set {
                this.directoryVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class BICDirectoryEntryType {
        
        private ParticipantInfoType participantInfoField;
        
        private SWBICList[] sWBICSField;
        
        private AccountsType[] accountsField;
        
        private string bICField;
        
        private ChangeType changeTypeField;
        
        private bool changeTypeFieldSpecified;
        
        /// <remarks/>
        public ParticipantInfoType ParticipantInfo {
            get {
                return this.participantInfoField;
            }
            set {
                this.participantInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SWBICS")]
        public SWBICList[] SWBICS {
            get {
                return this.sWBICSField;
            }
            set {
                this.sWBICSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accounts")]
        public AccountsType[] Accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChangeType ChangeType {
            get {
                return this.changeTypeField;
            }
            set {
                this.changeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChangeTypeSpecified {
            get {
                return this.changeTypeFieldSpecified;
            }
            set {
                this.changeTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ParticipantInfoType {
        
        private RstrListType[] rstrListField;
        
        private string namePField;
        
        private string englNameField;
        
        private string regNField;
        
        private string cntrCdField;
        
        private string rgnField;
        
        private string indField;
        
        private string tnpField;
        
        private string nnpField;
        
        private string adrField;
        
        private string prntBICField;
        
        private System.DateTime dateInField;
        
        private System.DateTime dateOutField;
        
        private bool dateOutFieldSpecified;
        
        private string ptTypeField;
        
        private string srvcsField;
        
        private string xchTypeField;
        
        private string uIDField;
        
        private ParticipantStatusType participantStatusField;
        
        private bool participantStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RstrList")]
        public RstrListType[] RstrList {
            get {
                return this.rstrListField;
            }
            set {
                this.rstrListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameP {
            get {
                return this.namePField;
            }
            set {
                this.namePField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EnglName {
            get {
                return this.englNameField;
            }
            set {
                this.englNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegN {
            get {
                return this.regNField;
            }
            set {
                this.regNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CntrCd {
            get {
                return this.cntrCdField;
            }
            set {
                this.cntrCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rgn {
            get {
                return this.rgnField;
            }
            set {
                this.rgnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ind {
            get {
                return this.indField;
            }
            set {
                this.indField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tnp {
            get {
                return this.tnpField;
            }
            set {
                this.tnpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nnp {
            get {
                return this.nnpField;
            }
            set {
                this.nnpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrntBIC {
            get {
                return this.prntBICField;
            }
            set {
                this.prntBICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateIn {
            get {
                return this.dateInField;
            }
            set {
                this.dateInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateOut {
            get {
                return this.dateOutField;
            }
            set {
                this.dateOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOutSpecified {
            get {
                return this.dateOutFieldSpecified;
            }
            set {
                this.dateOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PtType {
            get {
                return this.ptTypeField;
            }
            set {
                this.ptTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Srvcs {
            get {
                return this.srvcsField;
            }
            set {
                this.srvcsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string XchType {
            get {
                return this.xchTypeField;
            }
            set {
                this.xchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ParticipantStatusType ParticipantStatus {
            get {
                return this.participantStatusField;
            }
            set {
                this.participantStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParticipantStatusSpecified {
            get {
                return this.participantStatusFieldSpecified;
            }
            set {
                this.participantStatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class RstrListType {
        
        private RstrType rstrField;
        
        private System.DateTime rstrDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RstrType Rstr {
            get {
                return this.rstrField;
            }
            set {
                this.rstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime RstrDate {
            get {
                return this.rstrDateField;
            }
            set {
                this.rstrDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum RstrType {
        
        /// <remarks/>
        NORS,
        
        /// <remarks/>
        URRS,
        
        /// <remarks/>
        LWRS,
        
        /// <remarks/>
        LMRS,
        
        /// <remarks/>
        CLRS,
        
        /// <remarks/>
        FPRS,
        
        /// <remarks/>
        MRTR,
        
        /// <remarks/>
        SDRS,
        
        /// <remarks/>
        FPIP,
        
        /// <remarks/>
        ESRS,
        
        /// <remarks/>
        RSIP,
        
        /// <remarks/>
        FOCL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class InitialEDInfo {
        
        private EDRefID eDRefIDField;
        
        private string packetStatusField;
        
        /// <remarks/>
        public EDRefID EDRefID {
            get {
                return this.eDRefIDField;
            }
            set {
                this.eDRefIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PacketStatus {
            get {
                return this.packetStatusField;
            }
            set {
                this.packetStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EDWithDeclaration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PacketEDWithPartInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithMandatoryEDReceiver))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithEDSender))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDWithPartInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED807))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EPDComplete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class EDRefID {
        
        private string eDNoField;
        
        private System.DateTime eDDateField;
        
        private string eDAuthorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string EDNo {
            get {
                return this.eDNoField;
            }
            set {
                this.eDNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime EDDate {
            get {
                return this.eDDateField;
            }
            set {
                this.eDDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EDAuthor {
            get {
                return this.eDAuthorField;
            }
            set {
                this.eDAuthorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EDWithDeclaration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PacketEDWithPartInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithMandatoryEDReceiver))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithEDSender))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDWithPartInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED807))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EPDComplete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ED : EDRefID {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class EDWithDeclaration : ED {
        
        private System.DateTime declarationDateField;
        
        private string declarationNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DeclarationDate {
            get {
                return this.declarationDateField;
            }
            set {
                this.declarationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string DeclarationNo {
            get {
                return this.declarationNoField;
            }
            set {
                this.declarationNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class PacketEDWithPartInfo : ED {
        
        private PartInfo partInfoField;
        
        private EDRefID initialEDField;
        
        /// <remarks/>
        public PartInfo PartInfo {
            get {
                return this.partInfoField;
            }
            set {
                this.partInfoField = value;
            }
        }
        
        /// <remarks/>
        public EDRefID InitialED {
            get {
                return this.initialEDField;
            }
            set {
                this.initialEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class PartInfo {
        
        private string partNoField;
        
        private string partQuantityField;
        
        private string partAggregateIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string PartNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string PartQuantity {
            get {
                return this.partQuantityField;
            }
            set {
                this.partQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PartAggregateID {
            get {
                return this.partAggregateIDField;
            }
            set {
                this.partAggregateIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithEDSender))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ESWithMandatoryEDReceiver : ED {
        
        private string eDReceiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EDReceiver {
            get {
                return this.eDReceiverField;
            }
            set {
                this.eDReceiverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ESWithEDSender : ESWithMandatoryEDReceiver {
        
        private string eDSenderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EDSender {
            get {
                return this.eDSenderField;
            }
            set {
                this.eDSenderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDWithPartInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED807))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ESID : ED {
        
        private string eDReceiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EDReceiver {
            get {
                return this.eDReceiverField;
            }
            set {
                this.eDReceiverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ESIDResponse : ESID {
        
        private InitialEDInfo initialEDInfoField;
        
        private EDRefID initialEDField;
        
        /// <remarks/>
        public InitialEDInfo InitialEDInfo {
            get {
                return this.initialEDInfoField;
            }
            set {
                this.initialEDInfoField = value;
            }
        }
        
        /// <remarks/>
        public EDRefID InitialED {
            get {
                return this.initialEDField;
            }
            set {
                this.initialEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED807))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class ESIDWithPartInfo : ESID {
        
        private PartInfo partInfoField;
        
        private EDRefID initialEDField;
        
        /// <remarks/>
        public PartInfo PartInfo {
            get {
                return this.partInfoField;
            }
            set {
                this.partInfoField = value;
            }
        }
        
        /// <remarks/>
        public EDRefID InitialED {
            get {
                return this.initialEDField;
            }
            set {
                this.initialEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class EPDComplete : ED {
        
        private SettleNotEarlier settleNotEarlierField;
        
        private SettleNotLater settleNotLaterField;
        
        private AccDocRefID accDocField;
        
        private PayerRU payerField;
        
        private PayeeRU payeeField;
        
        private string eDReceiverField;
        
        private string paytKindField;
        
        private string sumField;
        
        private string paymentPrecedenceField;
        
        private System.DateTime reqSettlementDateField;
        
        private bool reqSettlementDateFieldSpecified;
        
        private string codePurposeField;
        
        /// <remarks/>
        public SettleNotEarlier SettleNotEarlier {
            get {
                return this.settleNotEarlierField;
            }
            set {
                this.settleNotEarlierField = value;
            }
        }
        
        /// <remarks/>
        public SettleNotLater SettleNotLater {
            get {
                return this.settleNotLaterField;
            }
            set {
                this.settleNotLaterField = value;
            }
        }
        
        /// <remarks/>
        public AccDocRefID AccDoc {
            get {
                return this.accDocField;
            }
            set {
                this.accDocField = value;
            }
        }
        
        /// <remarks/>
        public PayerRU Payer {
            get {
                return this.payerField;
            }
            set {
                this.payerField = value;
            }
        }
        
        /// <remarks/>
        public PayeeRU Payee {
            get {
                return this.payeeField;
            }
            set {
                this.payeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EDReceiver {
            get {
                return this.eDReceiverField;
            }
            set {
                this.eDReceiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PaytKind {
            get {
                return this.paytKindField;
            }
            set {
                this.paytKindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PaymentPrecedence {
            get {
                return this.paymentPrecedenceField;
            }
            set {
                this.paymentPrecedenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ReqSettlementDate {
            get {
                return this.reqSettlementDateField;
            }
            set {
                this.reqSettlementDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReqSettlementDateSpecified {
            get {
                return this.reqSettlementDateFieldSpecified;
            }
            set {
                this.reqSettlementDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodePurpose {
            get {
                return this.codePurposeField;
            }
            set {
                this.codePurposeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class SettleNotEarlier {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SessionID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("SettlementTime", typeof(System.DateTime), DataType="time")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class SettleNotLater {
        
        private System.DateTime settlementTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime SettlementTime {
            get {
                return this.settlementTimeField;
            }
            set {
                this.settlementTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class AccDocRefID {
        
        private string accDocNoField;
        
        private System.DateTime accDocDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AccDocNo {
            get {
                return this.accDocNoField;
            }
            set {
                this.accDocNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime AccDocDate {
            get {
                return this.accDocDateField;
            }
            set {
                this.accDocDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class PayerRU {
        
        private string nameField;
        
        private BankRU bankField;
        
        private string personalAccField;
        
        private string iNNField;
        
        private string kPPField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public BankRU Bank {
            get {
                return this.bankField;
            }
            set {
                this.bankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PersonalAcc {
            get {
                return this.personalAccField;
            }
            set {
                this.personalAccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KPP {
            get {
                return this.kPPField;
            }
            set {
                this.kPPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class BankRU {
        
        private string bICField;
        
        private string correspAccField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CorrespAcc {
            get {
                return this.correspAccField;
            }
            set {
                this.correspAccField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class PayeeRU {
        
        private string nameField;
        
        private BankRU bankField;
        
        private string personalAccField;
        
        private string iNNField;
        
        private string kPPField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public BankRU Bank {
            get {
                return this.bankField;
            }
            set {
                this.bankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PersonalAcc {
            get {
                return this.personalAccField;
            }
            set {
                this.personalAccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KPP {
            get {
                return this.kPPField;
            }
            set {
                this.kPPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class AccRstrListType {
        
        private RstrType accRstrField;
        
        private System.DateTime accRstrDateField;
        
        private string successorBICField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RstrType AccRstr {
            get {
                return this.accRstrField;
            }
            set {
                this.accRstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime AccRstrDate {
            get {
                return this.accRstrDateField;
            }
            set {
                this.accRstrDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SuccessorBIC {
            get {
                return this.successorBICField;
            }
            set {
                this.successorBICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class AccountsType {
        
        private AccRstrListType[] accRstrListField;
        
        private string accountField;
        
        private AccountType regulationAccountTypeField;
        
        private string ckField;
        
        private string accountCBRBICField;
        
        private System.DateTime dateInField;
        
        private System.DateTime dateOutField;
        
        private bool dateOutFieldSpecified;
        
        private AccountStatusType accountStatusField;
        
        private bool accountStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccRstrList")]
        public AccRstrListType[] AccRstrList {
            get {
                return this.accRstrListField;
            }
            set {
                this.accRstrListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccountType RegulationAccountType {
            get {
                return this.regulationAccountTypeField;
            }
            set {
                this.regulationAccountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CK {
            get {
                return this.ckField;
            }
            set {
                this.ckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AccountCBRBIC {
            get {
                return this.accountCBRBICField;
            }
            set {
                this.accountCBRBICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateIn {
            get {
                return this.dateInField;
            }
            set {
                this.dateInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateOut {
            get {
                return this.dateOutField;
            }
            set {
                this.dateOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOutSpecified {
            get {
                return this.dateOutFieldSpecified;
            }
            set {
                this.dateOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccountStatusType AccountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountStatusSpecified {
            get {
                return this.accountStatusFieldSpecified;
            }
            set {
                this.accountStatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum AccountType {
        
        /// <remarks/>
        BANA,
        
        /// <remarks/>
        CBRA,
        
        /// <remarks/>
        CRSA,
        
        /// <remarks/>
        TRSA,
        
        /// <remarks/>
        CLRA,
        
        /// <remarks/>
        EPGA,
        
        /// <remarks/>
        EPSA,
        
        /// <remarks/>
        GARA,
        
        /// <remarks/>
        TRUA,
        
        /// <remarks/>
        UTRA,
        
        /// <remarks/>
        CLAC,
        
        /// <remarks/>
        CBDC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum AccountStatusType {
        
        /// <remarks/>
        ACAC,
        
        /// <remarks/>
        ACDL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
    public partial class SWBICList {
        
        private string sWBICField;
        
        private bool defaultSWBICField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SWBIC {
            get {
                return this.sWBICField;
            }
            set {
                this.sWBICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DefaultSWBIC {
            get {
                return this.defaultSWBICField;
            }
            set {
                this.defaultSWBICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum ParticipantStatusType {
        
        /// <remarks/>
        PSAC,
        
        /// <remarks/>
        PSDL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum ChangeType {
        
        /// <remarks/>
        ADDD,
        
        /// <remarks/>
        CHGD,
        
        /// <remarks/>
        NCNG,
        
        /// <remarks/>
        DLTD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum ReasonCodeType {
        
        /// <remarks/>
        ACCH,
        
        /// <remarks/>
        AICH,
        
        /// <remarks/>
        ALCH,
        
        /// <remarks/>
        APPA,
        
        /// <remarks/>
        RIRA,
        
        /// <remarks/>
        RIRP,
        
        /// <remarks/>
        RMAA,
        
        /// <remarks/>
        RMVA,
        
        /// <remarks/>
        RQST,
        
        /// <remarks/>
        SOBD,
        
        /// <remarks/>
        UIRA,
        
        /// <remarks/>
        UIRP,
        
        /// <remarks/>
        ARRD,
        
        /// <remarks/>
        ARRM,
        
        /// <remarks/>
        ARRS,
        
        /// <remarks/>
        EOBD,
        
        /// <remarks/>
        EOCC,
        
        /// <remarks/>
        ICLD,
        
        /// <remarks/>
        ICLM,
        
        /// <remarks/>
        ICLS,
        
        /// <remarks/>
        PCHD,
        
        /// <remarks/>
        CSCH,
        
        /// <remarks/>
        NSCH,
        
        /// <remarks/>
        FCBD,
        
        /// <remarks/>
        CIBD,
        
        /// <remarks/>
        PPAD,
        
        /// <remarks/>
        CHCN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:leaftypes:v2.0")]
    public enum RequestCodeType {
        
        /// <remarks/>
        FIRR,
        
        /// <remarks/>
        SIRR,
        
        /// <remarks/>
        PROF,
    }
}
