
// This file has been generated by the GUI designer. Do not modify.
namespace QSBanks
{
	public partial class BankFilter
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton checkShowDeleted;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QSBanks.BankFilter
			global::Stetic.BinContainer.Attach (this);
			this.Name = "QSBanks.BankFilter";
			// Container child QSBanks.BankFilter.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkShowDeleted = new global::Gtk.CheckButton ();
			this.checkShowDeleted.CanFocus = true;
			this.checkShowDeleted.Name = "checkShowDeleted";
			this.checkShowDeleted.Label = global::Mono.Unix.Catalog.GetString ("Показывать удаленные");
			this.checkShowDeleted.DrawIndicator = true;
			this.checkShowDeleted.UseUnderline = true;
			this.hbox1.Add (this.checkShowDeleted);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkShowDeleted]));
			w1.Position = 0;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.checkShowDeleted.Toggled += new global::System.EventHandler (this.OnCheckShowDeletedToggled);
		}
	}
}
