
// This file has been generated by the GUI designer. Do not modify.
namespace QSOrmProject
{
	public partial class ReferenceRepresentation
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.HBox hboxSelect;
		
		private global::Gtk.Button buttonSelect;
		
		private global::Gtk.VSeparator vseparatorSelect;
		
		private global::Gtk.Button buttonAdd;
		
		private global::Gtk.Button buttonEdit;
		
		private global::Gtk.Button buttonDelete;
		
		private global::Gtk.CheckButton checkShowFilter;
		
		private global::Gtk.Button buttonRefresh;
		
		private global::Gtk.HBox hboxFilter;
		
		private global::Gtk.HBox hboxSearch;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry entrySearch;
		
		private global::Gamma.GtkWidgets.yLabel ylabelSearchAnd;
		
		private global::Gtk.Entry entrySearch2;
		
		private global::Gamma.GtkWidgets.yLabel ylabelSearchAnd2;
		
		private global::Gtk.Entry entrySearch3;
		
		private global::Gtk.Button buttonAddAnd;
		
		private global::Gtk.Button buttonSearchClear;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::QSOrmProject.RepresentationTreeView ormtableview;
		
		private global::Gtk.Label labelSum;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QSOrmProject.ReferenceRepresentation
			global::Stetic.BinContainer.Attach (this);
			this.Name = "QSOrmProject.ReferenceRepresentation";
			// Container child QSOrmProject.ReferenceRepresentation.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hboxSelect = new global::Gtk.HBox ();
			this.hboxSelect.Name = "hboxSelect";
			this.hboxSelect.Spacing = 6;
			// Container child hboxSelect.Gtk.Box+BoxChild
			this.buttonSelect = new global::Gtk.Button ();
			this.buttonSelect.Sensitive = false;
			this.buttonSelect.CanFocus = true;
			this.buttonSelect.Name = "buttonSelect";
			this.buttonSelect.UseUnderline = true;
			this.buttonSelect.Label = global::Mono.Unix.Catalog.GetString ("Выбрать");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-index", global::Gtk.IconSize.Menu);
			this.buttonSelect.Image = w1;
			this.hboxSelect.Add (this.buttonSelect);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxSelect [this.buttonSelect]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxSelect.Gtk.Box+BoxChild
			this.vseparatorSelect = new global::Gtk.VSeparator ();
			this.vseparatorSelect.Name = "vseparatorSelect";
			this.hboxSelect.Add (this.vseparatorSelect);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxSelect [this.vseparatorSelect]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add (this.hboxSelect);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hboxSelect]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonAdd = new global::Gtk.Button ();
			this.buttonAdd.CanFocus = true;
			this.buttonAdd.Name = "buttonAdd";
			this.buttonAdd.UseUnderline = true;
			this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("Добавить");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAdd.Image = w5;
			this.hbox1.Add (this.buttonAdd);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonAdd]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonEdit = new global::Gtk.Button ();
			this.buttonEdit.Sensitive = false;
			this.buttonEdit.CanFocus = true;
			this.buttonEdit.Name = "buttonEdit";
			this.buttonEdit.UseUnderline = true;
			this.buttonEdit.Label = global::Mono.Unix.Catalog.GetString ("Изменить");
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonEdit.Image = w7;
			this.hbox1.Add (this.buttonEdit);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonEdit]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonDelete = new global::Gtk.Button ();
			this.buttonDelete.Sensitive = false;
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			this.buttonDelete.Label = global::Mono.Unix.Catalog.GetString ("Удалить");
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.buttonDelete.Image = w9;
			this.hbox1.Add (this.buttonDelete);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonDelete]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkShowFilter = new global::Gtk.CheckButton ();
			this.checkShowFilter.CanFocus = true;
			this.checkShowFilter.Name = "checkShowFilter";
			this.checkShowFilter.Label = global::Mono.Unix.Catalog.GetString ("Фильтр");
			this.checkShowFilter.DrawIndicator = false;
			this.checkShowFilter.UseUnderline = true;
			this.hbox1.Add (this.checkShowFilter);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkShowFilter]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 4;
			w11.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonRefresh = new global::Gtk.Button ();
			this.buttonRefresh.CanFocus = true;
			this.buttonRefresh.Name = "buttonRefresh";
			this.buttonRefresh.UseUnderline = true;
			this.buttonRefresh.Label = global::Mono.Unix.Catalog.GetString ("Обновить");
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.buttonRefresh.Image = w12;
			this.hbox1.Add (this.buttonRefresh);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonRefresh]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxFilter = new global::Gtk.HBox ();
			this.hboxFilter.Name = "hboxFilter";
			this.hboxFilter.Spacing = 6;
			this.vbox1.Add (this.hboxFilter);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxFilter]));
			w15.Position = 1;
			w15.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxSearch = new global::Gtk.HBox ();
			this.hboxSearch.Name = "hboxSearch";
			this.hboxSearch.Spacing = 6;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Поиск:");
			this.hboxSearch.Add (this.label1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.label1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch = new global::Gtk.Entry ();
			this.entrySearch.CanFocus = true;
			this.entrySearch.Name = "entrySearch";
			this.entrySearch.IsEditable = true;
			this.entrySearch.InvisibleChar = '●';
			this.hboxSearch.Add (this.entrySearch);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.entrySearch]));
			w17.Position = 1;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.ylabelSearchAnd = new global::Gamma.GtkWidgets.yLabel ();
			this.ylabelSearchAnd.Name = "ylabelSearchAnd";
			this.ylabelSearchAnd.LabelProp = global::Mono.Unix.Catalog.GetString ("и");
			this.hboxSearch.Add (this.ylabelSearchAnd);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.ylabelSearchAnd]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch2 = new global::Gtk.Entry ();
			this.entrySearch2.CanFocus = true;
			this.entrySearch2.Name = "entrySearch2";
			this.entrySearch2.IsEditable = true;
			this.entrySearch2.InvisibleChar = '●';
			this.hboxSearch.Add (this.entrySearch2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.entrySearch2]));
			w19.Position = 3;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.ylabelSearchAnd2 = new global::Gamma.GtkWidgets.yLabel ();
			this.ylabelSearchAnd2.Name = "ylabelSearchAnd2";
			this.ylabelSearchAnd2.LabelProp = global::Mono.Unix.Catalog.GetString ("и");
			this.hboxSearch.Add (this.ylabelSearchAnd2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.ylabelSearchAnd2]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.entrySearch3 = new global::Gtk.Entry ();
			this.entrySearch3.CanFocus = true;
			this.entrySearch3.Name = "entrySearch3";
			this.entrySearch3.IsEditable = true;
			this.entrySearch3.InvisibleChar = '●';
			this.hboxSearch.Add (this.entrySearch3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.entrySearch3]));
			w21.Position = 5;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.buttonAddAnd = new global::Gtk.Button ();
			this.buttonAddAnd.CanFocus = true;
			this.buttonAddAnd.Name = "buttonAddAnd";
			this.buttonAddAnd.UseUnderline = true;
			this.buttonAddAnd.Label = global::Mono.Unix.Catalog.GetString ("И");
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddAnd.Image = w22;
			this.hboxSearch.Add (this.buttonAddAnd);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.buttonAddAnd]));
			w23.Position = 6;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hboxSearch.Gtk.Box+BoxChild
			this.buttonSearchClear = new global::Gtk.Button ();
			this.buttonSearchClear.TooltipMarkup = "Очистить";
			this.buttonSearchClear.CanFocus = true;
			this.buttonSearchClear.Name = "buttonSearchClear";
			this.buttonSearchClear.UseUnderline = true;
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.buttonSearchClear.Image = w24;
			this.hboxSearch.Add (this.buttonSearchClear);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hboxSearch [this.buttonSearchClear]));
			w25.Position = 7;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox1.Add (this.hboxSearch);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxSearch]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ormtableview = new global::QSOrmProject.RepresentationTreeView ();
			this.ormtableview.CanFocus = true;
			this.ormtableview.Name = "ormtableview";
			this.GtkScrolledWindow.Add (this.ormtableview);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w28.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelSum = new global::Gtk.Label ();
			this.labelSum.Name = "labelSum";
			this.labelSum.Xpad = 6;
			this.labelSum.Xalign = 1F;
			this.labelSum.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.labelSum.SingleLineMode = true;
			this.vbox1.Add (this.labelSum);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelSum]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.checkShowFilter.Hide ();
			this.hboxFilter.Hide ();
			this.ylabelSearchAnd.Hide ();
			this.entrySearch2.Hide ();
			this.ylabelSearchAnd2.Hide ();
			this.entrySearch3.Hide ();
			this.Hide ();
			this.buttonSelect.Clicked += new global::System.EventHandler (this.OnButtonSelectClicked);
			this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
			this.buttonEdit.Clicked += new global::System.EventHandler (this.OnButtonEditClicked);
			this.buttonDelete.Clicked += new global::System.EventHandler (this.OnButtonDeleteClicked);
			this.buttonRefresh.Clicked += new global::System.EventHandler (this.OnButtonRefreshClicked);
			this.checkShowFilter.Toggled += new global::System.EventHandler (this.OnCheckShowFilterToggled);
			this.entrySearch.Changed += new global::System.EventHandler (this.OnEntrySearchChanged);
			this.entrySearch2.Changed += new global::System.EventHandler (this.OnEntrySearch2Changed);
			this.entrySearch3.Changed += new global::System.EventHandler (this.OnEntrySearch3Changed);
			this.buttonAddAnd.Clicked += new global::System.EventHandler (this.OnButtonAddAndClicked);
			this.buttonSearchClear.Clicked += new global::System.EventHandler (this.OnButtonSearchClearClicked);
			this.ormtableview.RowActivated += new global::Gtk.RowActivatedHandler (this.OnOrmtableviewRowActivated);
			this.ormtableview.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnOrmtableviewButtonReleaseEvent);
		}
	}
}
