
// This file has been generated by the GUI designer. Do not modify.
namespace QSOrmProject.Permissions
{
	public partial class PermissionMatrixView
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Table tableAccsessMatrix;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QSOrmProject.Permissions.PermissionMatrixView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QSOrmProject.Permissions.PermissionMatrixView";
			// Container child QSOrmProject.Permissions.PermissionMatrixView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tableAccsessMatrix = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.tableAccsessMatrix.Name = "tableAccsessMatrix";
			this.tableAccsessMatrix.RowSpacing = ((uint)(6));
			this.tableAccsessMatrix.ColumnSpacing = ((uint)(6));
			this.hbox1.Add(this.tableAccsessMatrix);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.tableAccsessMatrix]));
			w1.Position = 0;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w2.Position = 0;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
