
// This file has been generated by the GUI designer. Do not modify.
namespace QSOrmProject
{
	public partial class OneWidgetDialog
	{
		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QSOrmProject.OneWidgetDialog
			this.Name = "QSOrmProject.OneWidgetDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child QSOrmProject.OneWidgetDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Internal child QSOrmProject.OneWidgetDialog.ActionArea
			global::Gtk.HButtonBox w2 = this.ActionArea;
			w2.Name = "dialog1_ActionArea";
			w2.Spacing = 10;
			w2.BorderWidth = ((uint)(5));
			w2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseStock = true;
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = "gtk-close";
			this.AddActionWidget(this.buttonClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w2[this.buttonClose]));
			w3.Expand = false;
			w3.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 106;
			this.DefaultHeight = 62;
			this.Show();
		}
	}
}
