
// This file has been generated by the GUI designer. Do not modify.
namespace QSChat
{
	public partial class ChatVSlider
	{
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.EventBox eventboxArrow;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Label labelMessageCount;
		
		private global::Gtk.Arrow arrowSlider;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.VSeparator vseparator2;
		
		private global::QSChat.Chat chat1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QSChat.ChatVSlider
			global::Stetic.BinContainer.Attach (this);
			this.Name = "QSChat.ChatVSlider";
			// Container child QSChat.ChatVSlider.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventboxArrow = new global::Gtk.EventBox ();
			this.eventboxArrow.Name = "eventboxArrow";
			// Container child eventboxArrow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.vbox4.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vseparator1]));
			w1.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelMessageCount = new global::Gtk.Label ();
			this.labelMessageCount.Name = "labelMessageCount";
			this.labelMessageCount.UseMarkup = true;
			this.vbox4.Add (this.labelMessageCount);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelMessageCount]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.arrowSlider = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(2)));
			this.arrowSlider.Name = "arrowSlider";
			this.vbox4.Add (this.arrowSlider);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.arrowSlider]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Онлайн чат");
			this.label1.SingleLineMode = true;
			this.label1.Angle = 90;
			this.vbox4.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label1]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.vbox4.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vseparator2]));
			w5.Position = 4;
			this.eventboxArrow.Add (this.vbox4);
			this.hbox2.Add (this.eventboxArrow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.eventboxArrow]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.chat1 = new global::QSChat.Chat ();
			this.chat1.WidthRequest = 386;
			this.chat1.Events = ((global::Gdk.EventMask)(256));
			this.chat1.Name = "chat1";
			this.chat1.IsHided = false;
			this.chat1.Active = false;
			this.hbox2.Add (this.chat1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.chat1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.eventboxArrow.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventboxArrowButtonPressEvent);
			this.chat1.ChatUpdated += new global::System.EventHandler (this.OnChat1ChatUpdated);
		}
	}
}
