
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Measurement.Views
{
	public partial class MeasurementUnitView
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button buttonSave;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Table datatable1;
		private global::Gamma.GtkWidgets.yEntry dataentryOKEI;
		private global::Gamma.GtkWidgets.yEntry entryName;
		private global::Gtk.Label labelOKEI;
		private global::Gtk.Label labelDigits;
		private global::Gtk.Label labelName;
		private global::Gamma.GtkWidgets.ySpinButton spinDigits;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach(this);
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w2, 0);
			this.Name = "QS.Measurement.Views.MeasurementUnitView";
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			this.hbox4.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonSave]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			this.hbox4.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.datatable1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.datatable1.Name = "datatable1";
			this.datatable1.RowSpacing = ((uint)(6));
			this.datatable1.ColumnSpacing = ((uint)(6));
			this.dataentryOKEI = new global::Gamma.GtkWidgets.yEntry();
			this.dataentryOKEI.CanFocus = true;
			this.dataentryOKEI.Name = "dataentryOKEI";
			this.dataentryOKEI.IsEditable = true;
			this.dataentryOKEI.MaxLength = 5;
			this.dataentryOKEI.InvisibleChar = '●';
			this.datatable1.Add(this.dataentryOKEI);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.datatable1[this.dataentryOKEI]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.entryName = new global::Gamma.GtkWidgets.yEntry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.MaxLength = 10;
			this.entryName.InvisibleChar = '●';
			this.datatable1.Add(this.entryName);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.datatable1[this.entryName]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.labelOKEI = new global::Gtk.Label();
			this.labelOKEI.Name = "labelOKEI";
			this.labelOKEI.Xalign = 1F;
			this.labelOKEI.LabelProp = global::Mono.Unix.Catalog.GetString("Код ОКЕИ:");
			this.datatable1.Add(this.labelOKEI);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.datatable1[this.labelOKEI]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.labelDigits = new global::Gtk.Label();
			this.labelDigits.Name = "labelDigits";
			this.labelDigits.Xalign = 1F;
			this.labelDigits.LabelProp = global::Mono.Unix.Catalog.GetString("Знаков после запятой:");
			this.labelDigits.Justify = ((global::Gtk.Justification)(1));
			this.datatable1.Add(this.labelDigits);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.datatable1[this.labelDigits]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.labelName = new global::Gtk.Label();
			this.labelName.Name = "labelName";
			this.labelName.Xalign = 1F;
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString("Название:");
			this.datatable1.Add(this.labelName);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.datatable1[this.labelName]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.spinDigits = new global::Gamma.GtkWidgets.ySpinButton(0D, 5D, 1D);
			this.spinDigits.CanFocus = true;
			this.spinDigits.Name = "spinDigits";
			this.spinDigits.Adjustment.PageIncrement = 10D;
			this.spinDigits.ClimbRate = 1D;
			this.spinDigits.Numeric = true;
			this.spinDigits.ValueAsDecimal = 0m;
			this.spinDigits.ValueAsInt = 0;
			this.datatable1.Add(this.spinDigits);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.datatable1[this.spinDigits]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add(this.datatable1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.datatable1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox3);
			if(this.Child != null) {
				this.Child.ShowAll();
			}
			w1.SetUiManager(UIManager);
			this.Hide();
		}
	}
}
