syntax = "proto3";

package QS.Cloud.Core;

service DataBaseManagement{
	rpc CheckDataBaseExists (CheckDataBaseExistsRequest) returns (CheckDataBaseExistsResponse);
	rpc ClearDataBase (ClearDataBaseRequest) returns (ClearDataBaseResponse);
	// Создать пустую базу
	rpc CreateDataBase (CreateDataBaseRequest) returns (CreateDataBaseResponse);
	// Удалить базу и очистить реестр
	rpc DropDataBase (DropDataBaseRequest) returns (DropDataBaseResponse);
}

message ClearDataBaseRequest{
	int32 base_id = 1;
	uint32 product_id = 2;
}

message ClearDataBaseResponse{
	bool success = 1;
}

message CheckDataBaseExistsRequest{
	string name = 1;
	uint32 product_id = 2;
}

message CheckDataBaseExistsResponse{
	bool exists = 1;
	optional int32 base_id = 2;
}

message CreateDataBaseRequest{
	string name = 1;
	string title = 2;
	uint32 product_id = 3;
}

message CreateDataBaseResponse{
	int32 base_id = 1;
	string base_guid = 2;
}

message DropDataBaseRequest{
	int32 base_id = 1;
	uint32 product_id = 2;
}

message DropDataBaseResponse{
	bool success = 1;
}
