
// This file has been generated by the GUI designer. Do not modify.
namespace QS.Updater.App.Views
{
	public partial class NewVersionView
	{
		private global::Gtk.VBox vbox2;

		private global::Gamma.GtkWidgets.yLabel labelMainInfo;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTable tableReleases;

		private global::Gamma.GtkWidgets.yHBox hboxSelectRelease;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.Widgets.yListComboBox comboSelectInstaller;

		private global::Gamma.GtkWidgets.yLabel labelDBUpdateInfo;

		private global::Gtk.HButtonBox dialog1_ActionArea;

		private global::Gtk.Button buttonSkip;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QS.Updater.App.Views.NewVersionView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "QS.Updater.App.Views.NewVersionView";
			// Container child QS.Updater.App.Views.NewVersionView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelMainInfo = new global::Gamma.GtkWidgets.yLabel();
			this.labelMainInfo.Name = "labelMainInfo";
			this.labelMainInfo.LabelProp = global::Mono.Unix.Catalog.GetString("ylabel1");
			this.vbox2.Add(this.labelMainInfo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelMainInfo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.HeightRequest = 400;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tableReleases = new global::Gamma.GtkWidgets.yTable();
			this.tableReleases.Name = "tableReleases";
			this.tableReleases.NRows = ((uint)(3));
			this.tableReleases.NColumns = ((uint)(3));
			this.tableReleases.RowSpacing = ((uint)(6));
			this.tableReleases.ColumnSpacing = ((uint)(6));
			w2.Add(this.tableReleases);
			this.GtkScrolledWindow.Add(w2);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w5.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hboxSelectRelease = new global::Gamma.GtkWidgets.yHBox();
			this.hboxSelectRelease.Name = "hboxSelectRelease";
			this.hboxSelectRelease.Spacing = 6;
			// Container child hboxSelectRelease.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Использовать установщик версии:");
			this.hboxSelectRelease.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxSelectRelease[this.ylabel1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hboxSelectRelease.Gtk.Box+BoxChild
			this.comboSelectInstaller = new global::Gamma.Widgets.yListComboBox();
			this.comboSelectInstaller.Name = "comboSelectInstaller";
			this.comboSelectInstaller.AddIfNotExist = false;
			this.comboSelectInstaller.DefaultFirst = false;
			this.hboxSelectRelease.Add(this.comboSelectInstaller);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxSelectRelease[this.comboSelectInstaller]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add(this.hboxSelectRelease);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxSelectRelease]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelDBUpdateInfo = new global::Gamma.GtkWidgets.yLabel();
			this.labelDBUpdateInfo.Name = "labelDBUpdateInfo";
			this.labelDBUpdateInfo.LabelProp = global::Mono.Unix.Catalog.GetString("ylabel2");
			this.vbox2.Add(this.labelDBUpdateInfo);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelDBUpdateInfo]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.dialog1_ActionArea = new global::Gtk.HButtonBox();
			this.dialog1_ActionArea.Name = "dialog1_ActionArea";
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonSkip = new global::Gtk.Button();
			this.buttonSkip.CanFocus = true;
			this.buttonSkip.Name = "buttonSkip";
			this.buttonSkip.UseUnderline = true;
			this.buttonSkip.Label = global::Mono.Unix.Catalog.GetString("Пропустить обновление");
			this.dialog1_ActionArea.Add(this.buttonSkip);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.buttonSkip]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Напомнить позже");
			this.dialog1_ActionArea.Add(this.buttonCancel);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.buttonCancel]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("Скачать и установить");
			this.dialog1_ActionArea.Add(this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.buttonOk]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox2.Add(this.dialog1_ActionArea);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.dialog1_ActionArea]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.buttonSkip.Clicked += new global::System.EventHandler(this.OnButtonSkipClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
