<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks Condition="'$(MSBuildRuntimeType)' == 'Core'">netstandard2.0;net10.0</TargetFrameworks>
    <TargetFramework Condition="'$(MSBuildRuntimeType)' != 'Core'">netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<LangVersion>7.3</LangVersion>
  </PropertyGroup>
	<PropertyGroup Label="Avalonia">
		<AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Assets\mariadb.png" />
	  <None Remove="Assets\qs.ico" />
	  <None Remove="Assets\sps.png" />
	  <None Remove="Assets\sps1024.png" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	  <PackageReference Condition="'$(TargetFramework)' == 'netstandard2.0'" Include="ReactiveUI" Version="22.3.1" />
	  <PackageReference Condition="'$(TargetFramework)' == 'net10.0'" Include="ReactiveUI" Version="24.2.0" />
	  <PackageReference Condition="'$(TargetFramework)' == 'net10.0'" Include="System.Reactive" Version="7.0.0" ExcludeAssets="analyzers" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\QS.Configuration\QS.Configuration.csproj" />
	  <ProjectReference Include="..\QS.DbManagement\QS.DbManagement.csproj" />
	  <ProjectReference Include="..\QS.Project.Core\QS.Project.Core.csproj" />
	  <ProjectReference Include="..\QS.Project.Desktop\QS.Project.Desktop.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Assets\mariadb.png">
	  </Resource>
	  <EmbeddedResource Include="Assets\qs.ico">
	  </EmbeddedResource>
	</ItemGroup>

</Project>
